using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using TMPro;

public class BossWarning : MonoBehaviour
{
    [SerializeField]
    private float lerpTime = 0.1f;
    private TextMeshProUGUI textWarning;
    private void Awake()
    {
        textWarning = GetComponent<TextMeshProUGUI>();
    }
    private void OnEnable()
    {
        StartCoroutine("ColorLerpLoop");
    }
    private void OnDisable()
    {
        
    }
    private IEnumerator ColorLerpLoop()
    {
        while(true)
        {
            yield return StartCoroutine(ColorLerp(Color.white, Color.red));
            yield return StartCoroutine(ColorLerp(Color.red, Color.white));
        }
    }
    private IEnumerator ColorLerp(Color startColor,Color endColor)
    {
        float currentTime = 0;
        float percent = 0;

        while(percent < 1)
        {
            currentTime += Time.deltaTime;
            percent = currentTime / lerpTime;
            textWarning.color = Color.Lerp(startColor, endColor, percent);
            yield return null;
        }
    }
}
